### ISSUE TITLE
Mentions plugin throws exceptions when deleting text

### ISSUE THREAD

**Issue by jbalinski** [ckeditor/ckeditor4#3356]
## Are you reporting a feature request or a bug?
Bug

## Provide detailed reproduction steps (if any)
1. Testing with the CKEditor 4.12.1 with the mentions plugin.  Using Chrome 76.
2. Have an asynchronous callback setup to get the mention entries from a web service.
3.  Trigger the Mentions plugin by typing "@" followed by text that matches entries from the web service.
4. Select one of the entries.
5. Now use the backspace key multiple times quickly to delete the text that was entered.
6. The following exception is triggered.

`ckeditor.js:192 Uncaught DOMException: Failed to execute 'setEnd' on 'Range': The offset 69 is larger than the node's length (68).
    at window.CKEDITOR.window.CKEDITOR.dom.CKEDITOR.dom.range.getClientRects (https://ckeditor.com/docs/vendors/4.12.1/ckeditor/ckeditor.js:192:3)
    at getViewPosition (https://ckeditor.com/docs/vendors/4.12.1/ckeditor/plugins/autocomplete/plugin.js?t=J7QH:15:414)
    at g.updatePosition (https://ckeditor.com/docs/vendors/4.12.1/ckeditor/plugins/autocomplete/plugin.js?t=J7QH:18:505)
    at f.viewRepositionListener (https://ckeditor.com/docs/vendors/4.12.1/ckeditor/plugins/autocomplete/plugin.js?t=J7QH:12:111)
    at f.<anonymous> (https://ckeditor.com/docs/vendors/4.12.1/ckeditor/plugins/autocomplete/plugin.js?t=J7QH:9:368)
    at a.h (https://ckeditor.com/docs/vendors/4.12.1/ckeditor/ckeditor.js:10:70)
    at a.<anonymous> (https://ckeditor.com/docs/vendors/4.12.1/ckeditor/ckeditor.js:11:433)
    at a.window.CKEDITOR.window.CKEDITOR.dom.CKEDITOR.editor.CKEDITOR.editor.fire (https://ckeditor.com/docs/vendors/4.12.1/ckeditor/ckeditor.js:13:97)
    at CKEDITOR.plugins.undo.UndoManager.type (https://ckeditor.com/docs/vendors/4.12.1/ckeditor/ckeditor.js:1097:449)
    at CKEDITOR.plugins.undo.NativeEditingHandler.onKeyup (https://ckeditor.com/docs/vendors/4.12.1/ckeditor/ckeditor.js:1108:212)`

Note that this can be triggered on the demo page for the CKEditor control:
https://ckeditor.com/docs/ckeditor4/latest/examples/mentions.html

### Expected result
No exceptions

### Actual result
Exceptions

## Other details

* Browser: Chrome 76
* OS: Windows 10 1809
* CKEditor version: 4.12.1
* Installed CKEditor plugins: Mentions

**Comment by KarolDawidziuk** [comment]
I close this issue because we have a new one with more details. See #5036.
