### ISSUE TITLE
Failed to execute 'appendChild' on 'Node' when deleting <ol> from <ul>

### ISSUE THREAD

**Issue by Geo-T** [ckeditor/ckeditor4#3934]
## Type of report

Bug

## Provide detailed reproduction steps

Create a two level list as follow:
![image](https://user-images.githubusercontent.com/10050616/76768437-4b59f580-679b-11ea-8ebf-ad37359f526a.png)

On the empty sublist item, add an ordered list:
![image](https://user-images.githubusercontent.com/10050616/76768529-6c224b00-679b-11ea-89d4-e456460b4519.png)

Delete the last line with two backspace, it will produce the following error in the console:

`Uncaught DOMException: Failed to execute 'appendChild' on 'Node': The new child element contains the parent.
    at CKEDITOR.dom.element.append (https://ckeditor.com/assets/libs/ckeditor4/4.14.0/ckeditor.js:97:300)
    at l (https://ckeditor.com/assets/libs/ckeditor4/4.14.0/ckeditor.js:1132:15)
    at a.<anonymous> (https://ckeditor.com/assets/libs/ckeditor4/4.14.0/ckeditor.js:1147:282)
    at a.c (https://ckeditor.com/assets/libs/ckeditor4/4.14.0/ckeditor.js:10:70)
    at a.<anonymous> (https://ckeditor.com/assets/libs/ckeditor4/4.14.0/ckeditor.js:11:433)
    at a.CKEDITOR.editor.CKEDITOR.editor.fire (https://ckeditor.com/assets/libs/ckeditor4/4.14.0/ckeditor.js:13:97)
    at CKEDITOR.keystrokeHandler.g (https://ckeditor.com/assets/libs/ckeditor4/4.14.0/ckeditor.js:249:395)
    at $.c (https://ckeditor.com/assets/libs/ckeditor4/4.14.0/ckeditor.js:10:70)
    at $.fire (https://ckeditor.com/assets/libs/ckeditor4/4.14.0/ckeditor.js:11:433)
    at HTMLBodyElement.<anonymous> (https://ckeditor.com/assets/libs/ckeditor4/4.14.0/ckeditor.js:68:412)`

You can reproduce this bug on the demo page: https://ckeditor.com/ckeditor-4/demo/

**Comment by Dumluregn** [comment]
Thank you for report. It's reproducible also on CDN and at least as old as `4.7.0` (didn't check former versions).
