### ISSUE TITLE
Failed to execute 'setStart' on 'Range': The offset X is larger than the node's length (Y).

### ISSUE THREAD

**Issue by hasmats** [ckeditor/ckeditor4#4229]
## Type of report

Bug

## Reproduction steps

1. Open CKEditor demo https://ckeditor.com/docs/ckeditor4/latest/examples/size.html
2. Place cursor after the heading and hit Shift+Enter
3. Move focus out of the editor
4. Back focus and type "test"
5. Select "test" and apply Heading 2

### Expected result

"Heading 2" is applied to the selected text

### Actual result

The error below is thrown and also the selected text and the line above are now both "Heading 2"

```
ckeditor.js:450 Uncaught DOMException: Failed to execute 'setStart' on 'Range': The offset 7 is larger than the node's length (3).
    at x (http://cdn.ckeditor.com/4.13.1/full/ckeditor.js:450:240)
    at a.<anonymous> (http://cdn.ckeditor.com/4.13.1/full/ckeditor.js:465:396)
    at a.l (http://cdn.ckeditor.com/4.13.1/full/ckeditor.js:10:224)
    at a.<anonymous> (http://cdn.ckeditor.com/4.13.1/full/ckeditor.js:12:47)
    at a.CKEDITOR.editor.CKEDITOR.editor.fire (http://cdn.ckeditor.com/4.13.1/full/ckeditor.js:13:242)
    at a.h (http://cdn.ckeditor.com/4.13.1/full/ckeditor.js:448:8)
    at b.l (http://cdn.ckeditor.com/4.13.1/full/ckeditor.js:10:224)
    at b.fire (http://cdn.ckeditor.com/4.13.1/full/ckeditor.js:12:47)
    at CKEDITOR.dom.selection.selectRanges (http://cdn.ckeditor.com/4.13.1/full/ckeditor.js:488:153)
    at CKEDITOR.dom.range.select (http://cdn.ckeditor.com/4.13.1/full/ckeditor.js:468:129)
```

This was also reported 4 years ago on old issue-tracker https://dev.ckeditor.com/ticket/14895

**Comment by Comandeer** [comment]
I can't reproduce the issue, error is not showing up. Can you provide some info about the used browser?

> the selected text and the line above are now both "Heading 2"

It's connected with the fact that Shift + Enter produces line break (\`br\`), not the new heading. Due to that, applying block style to the second line of the heading, applies it to the whole heading.

**Comment by hasmats** [comment]
> I can't reproduce the issue, error is not showing up. Can you provide some info about the used browser?

I reproduced it in Chrome v84.0.4147.89 on macOS.

**Comment by Dumluregn** [comment]
Unfortunately I reproduced the issue:

![heading_chrome](https://user-images.githubusercontent.com/10883184/91951527-f7b77600-ed00-11ea-94ab-819853e1f8a1.gif)

It is present on Chromium-based browsers (Chrome, Edge, Opera) but not on FF.

**Comment by prerna-bhatra** [comment]
this happens because two  extra  adjacent  text nodes are added when we add mark in parent so use node.normalize to wrap the nodes

**Comment by KeitelDOG** [comment]
I don't use CkEditor, but I was having a hard time yesterday on this error. I know where it comes from. And in this case, it might be a bug, since the package is controlling the range operations.

Short story: The real reason this is happening is that when the node passed to `range.setStart(node, offset)` is a text node (`nodeType === 3` => text only) or similar, then everything is fine. But once the node is a (`nodeType === 1` => mix of tags + text), then it considers the offset as the index of QUANTITY of nodes inside.

It's documented on MOZILLA : https://developer.mozilla.org/en-US/docs/Web/API/Range/setStart :

> If the startNode is a Node of type Text, Comment, or CDataSection, then startOffset is the number of characters from the start of startNode. For other Node types, startOffset is the number of child nodes between the start of the startNode.

I realized that, when div contains only text, then passing `node.childNodes[0]` will work, as it passes a TextNode as single child. But once the div get a span tag for example inside, let's say `<div>Hello <span>World</span> coders!</div>`, the div node is having 3 childNodes `[text, span, text]`. And by passing only `node.childNodes[0]`, you only pass 1st TextNode with value `Hello `, 6 characters only, which is outside of range when you expect to deal with span node `World` and text node ` coders!`.

The solution for it is to check length of `node.childNodes` to see if there is multiple children (all text nodes or mixed tags + nodes), and loop each of them, to calculate any match with text you might want, and the RANGE INDEX would change accordingly to each `Child Node`. For example:

`Text Node => node.childNodes[0]=> "Hello " => index 0 to 5`
`Span Node => node.childNodes[1].firstChild => "World" => index 0 to 4`
`Text Node => node.childNodes[2] => " coders!" => index 0 to 7`

So if you want to select `coders`, you would have first loop, and detect that it is in 3rd node, and then call

    range.setStart(node.childNodes[2], 1);
    range.setEnd(node.childNodes[2], 6);
