### ISSUE TITLE
CKEDITOR.style.customHandlers[a.type] is not a constructor

### ISSUE THREAD

**Issue by anthonycalafate1** [ckeditor/ckeditor4#5053]
## Type of report

Help Required

## Provide detailed reproduction steps (if any)

<!--

I am running CKEditor V 4.17.1_basic

Code Samples

In the Header
<script type="text/javascript" src="../JavaScript/ckeditor/ckeditor.js"></script>

Text Area to Replace
<textarea id="txtremark" name="txtremark" runat="server" cols="50" rows="10"></textarea>

Last code on the page
        <script type="text/javascript">    
            CKEDITOR.config.autoGrow_minHeight = 100;
            CKEDITOR.config.autoGrow_maxHeight = 500;
            CKEDITOR.config.autoGrow_onStartup = true;
            CKEDITOR.replace('txtremark');
        </script>

When I run my asp page it loads but the text area is missing and the following error is in the console (Edge Browser).
        
    Uncaught TypeError: CKEDITOR.style.customHandlers[a.type] is not a constructor
    at new CKEDITOR.style (ckeditor.js:457:294)
    at a.<anonymous> (ckeditor.js:1010:520)
    at a.j (ckeditor.js:10:222)
    at a.<anonymous> (ckeditor.js:12:47)
    at a.CKEDITOR.editor.CKEDITOR.editor.fire (ckeditor.js:13:252)
    at a.<anonymous> (ckeditor.js:243:312)
    at a.<computed> (ckeditor.js:11:113)
    at a.j (ckeditor.js:10:222)
    at a.<anonymous> (ckeditor.js:12:47)
    at a.CKEDITOR.editor.CKEDITOR.editor.fire (ckeditor.js:13:252)

I am not sure what is causing this error. Any help would be appreciated.

Tony

**Comment by anthonycalafate1** [comment]
I am encountering the following error and need some help solving this.
Error is viewed in the console (edge) browser and is executed on form load
    
    Uncaught TypeError: CKEDITOR.style.customHandlers[a.type] is not a constructor
    at new CKEDITOR.style (ckeditor.js:457:294)
    at a.<anonymous> (ckeditor.js:1010:520)
    at a.j (ckeditor.js:10:222)
    at a.<anonymous> (ckeditor.js:12:47)
    at a.CKEDITOR.editor.CKEDITOR.editor.fire (ckeditor.js:13:252)
    at a.<anonymous> (ckeditor.js:243:312)
    at a.<computed> (ckeditor.js:11:113)
    at a.j (ckeditor.js:10:222)
    at a.<anonymous> (ckeditor.js:12:47)
    at a.CKEDITOR.editor.CKEDITOR.editor.fire (ckeditor.js:13:252)


CKEditor Config is as follows

Header
<script type="text/javascript" src="../JavaScript/ckeditor/ckeditor.js"></script>

Text Area
<textarea id="txtremark" name="txtremark" runat="server" cols="50" rows="10"></textarea>

Code:
        <script type="text/javascript">    
            CKEDITOR.config.autoGrow_minHeight = 100;
            CKEDITOR.config.autoGrow_maxHeight = 500;
            CKEDITOR.config.autoGrow_onStartup = true;
            CKEDITOR.replace('txtremark');
        </script>


Any help would be appreciated

**Comment by Comandeer** [comment]
Could you provide some simple reproduction of the bug and more information about the used version of Edge?

**Comment by anthonycalafate1** [comment]
I have found that this does not occur in IE.
Browser Versions:
- IE: 11.0.9600.20139
- Edge: 97.0.1072.69 (Official build) (64-bit)

I can provide apsx pages but do not want them hosted publicly

**Comment by anthonycalafate1** [comment]
I have attached am aspx page and the CKEditor files.
Additionally, I have tried installing the latest CKEditor files (v5) but I get the same error.

[CKIssue.zip](https://github.com/ckeditor/ckeditor4/files/7983436/CKIssue.zip)

**Comment by Comandeer** [comment]
I can't run the demo because several files are missing (including `styles.js`).
