### ISSUE TITLE
Error thrown when the editor is destroyed

### ISSUE THREAD

**Issue by Comandeer** [ckeditor/ckeditor4#5059]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. Open http://localhost:1030/tests/plugins/wysiwygarea/manual/mutationobserverdisconnected
2. Open the console.

### Expected result

There are no errors in the console.

### Actual result

There is an error:

```
ckeditor.js:36 Uncaught TypeError: Cannot read properties of null (reading 'find')
    at Object.getStyledSpans (ckeditor.js:36:150)
    at a.countColors (ckeditor.js:815:246)
    at Object.countColors (ckeditor.js:29:457)
    at a.renderContentColors (ckeditor.js:820:131)
    at a.<anonymous> (ckeditor.js:814:153)
    at a.<computed> (ckeditor.js:11:152)
    at a.e (ckeditor.js:10:246)
    at a.<anonymous> (ckeditor.js:12:91)
    at a.CKEDITOR.editor.CKEDITOR.editor.fire (ckeditor.js:13:286)
    at a.fireOnce (ckeditor.js:12:251)
```

## Other details

* Browser: Chrome 97
* OS: macOS
* CKEditor version: 4.17.2 (built)
* Installed CKEditor plugins: colorbutton

Both destroying and `renderContentColors` are bound to `instanceReady` listener. It seems that destroy is faster and `colorbutton` plugin does not contain any check if the editor is available.

**Comment by dufipl** [comment]
Reproduces also on Firefox.
