### ISSUE TITLE
Chrome: Failed to execute 'removeChild' on 'Node' when enabling and disabling source mode

### ISSUE THREAD

**Issue by dufipl** [ckeditor/ckeditor4#5425]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. Open [tests/plugins/widget/manual/block](http://0:0:0:0:1030/tests/plugins/widget/manual/block) or http://0:0:0:0:1030/tests/plugins/widget/manual/inline manual test
2. Enable source mode
3. Disable source mode

### Expected result

No errors in the console.

### Actual result

Error in the console:
```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'getManifest')
    at i (content.js:2:211240)
    at e.value (content.js:2:1277311)
    at e.value (content.js:2:1277166)
    at s.onAddModule (content.js:2:893691)
    at s.addModule (content.js:2:612466)
    at Or (content.js:2:1278060)
    at content.js:2:1278548
    at c (content.js:2:406899)
    at Generator._invoke (content.js:2:406652)
    at Generator.next (content.js:2:407258)
```

## Other details

* Browser: Chrome
* CKEditor version: 4.20.2

**Comment by Comandeer** [comment]
I can't reproduce the issue – it could be connected with some browser extension.
